# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_auto_20170223_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='likes',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', to='secrets.User'),
        ),
    ]
